// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mola.Models;

#nullable disable

namespace mola.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241229104154_mola")]
    partial class mola
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("mola.Models.Etkinlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnaResimUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Baslik")
                        .HasColumnType("longtext");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Text1")
                        .HasColumnType("longtext");

                    b.Property<string>("Text2")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Etkinliks");
                });

            modelBuilder.Entity("mola.Models.EtkinlikResim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EtkinlikId")
                        .HasColumnType("int");

                    b.Property<string>("ResimUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Etkinliksesims");
                });

            modelBuilder.Entity("mola.Models.Restoran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnaResimUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Baslik")
                        .HasColumnType("longtext");

                    b.Property<string>("Text1")
                        .HasColumnType("longtext");

                    b.Property<string>("Text2")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Restorans");
                });

            modelBuilder.Entity("mola.Models.RestoranResim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ResimUrl")
                        .HasColumnType("longtext");

                    b.Property<int>("RestoranId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RestoranResims");
                });

            modelBuilder.Entity("mola.Models.Spa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnaResimUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Baslik")
                        .HasColumnType("longtext");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Text1")
                        .HasColumnType("longtext");

                    b.Property<string>("Text2")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Spas");
                });

            modelBuilder.Entity("mola.Models.SpaResim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ResimUrl")
                        .HasColumnType("longtext");

                    b.Property<int>("SpaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SpaResims");
                });
#pragma warning restore 612, 618
        }
    }
}
